name: Test FastAPI Project

on:
  push:
    branches: [ main, feature/* ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install fastapi uvicorn

      - name: Test import FastAPI app
        run: |
          python -c "from api.main import app; print('App OK')"